### ISSUE TITLE
Issue with strange characters in FASTA file from the DRAMP database

### ISSUE THREAD

**Issue by sandraaran** [Darcy220606/AMPcombi#99]
When no database is specified, DRAMP is downloaded by default. However, lately, there is a sequence corresponding to DRAMP31926 that includes a character that is not a letter but rather the character 工 (U+5DE5), which causes AMPcombi to fail during execution.
  
here is the complete error:

  <--path-list> was not given, paths to AMP-results-files will be inferred
  <--AMP_database> was not given, the current DRAMP general-AMP database will be downloaded and used
  Traceback (most recent call last):
    File "/usr/local/bin/ampcombi", line 10, in <module>
      sys.exit(main())
               ^^^^^^
    File "/usr/local/bin/ampcombi.py", line 476, in main
      args.func(args)  # call the default function
      ^^^^^^^^^^^^^^^
    File "/usr/local/bin/ampcombi.py", line 455, in parse_table_log
      log_output('Ampcombi_parse_tables.log', args, parse_tables)
    File "/usr/local/bin/ampcombi.py", line 449, in log_output
      func(args)
    File "/usr/local/bin/ampcombi.py", line 231, in parse_tables
      db = check_ref_database(database)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/bin/check_input.py", line 65, in check_ref_database
      download_DRAMP(db)
    File "/usr/local/bin/amp_database.py", line 39, in download_DRAMP
      for record in seq_record:
    File "/usr/local/lib/python3.11/site-packages/Bio/SeqIO/Interfaces.py", line 72, in __next__
      return next(self.records)
             ^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/Bio/SeqIO/FastaIO.py", line 246, in iterate
      Seq(sequence), id=first_word, name=first_word, description=title
      ^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/Bio/Seq.py", line 2034, in __init__
      self._data = bytes(data, encoding="ASCII")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  UnicodeEncodeError: 'ascii' codec can't encode character '\u5de5' in position 20: ordinal not in range(128)

**Comment by Darcy220606** [comment]
Thank you for reporting the issue its now been addressed in PR #100
